# Generated by Django 2.2.2 on 2019-06-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20190621_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfolder',
            name='folder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myfiles.Folder'),
        ),
    ]
