# Generated by Django 2.2.2 on 2019-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('shared', '0004_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
