# Generated by Django 2.2.2 on 2019-06-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='current_usage_mb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='max_usage_mb',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
        ),
    ]
