# Generated by Django 2.2.2 on 2019-06-23 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20190621_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuota',
            new_name='UserInfo',
        ),
    ]
