# Generated by Django 2.2.2 on 2019-06-23 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20190623_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserPreferences',
        ),
    ]
