# Generated by Django 2.2.2 on 2019-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190623_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='Here is the name',
            field=models.IntegerField(default=60),
        ),
    ]
