# Generated by Django 2.2.2 on 2019-06-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userpreferences_here is the name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='Here is the name',
            new_name='Recyclebin Lifetime (Days)',
        ),
    ]
