# Generated by Django 2.2.2 on 2019-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190623_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='Recyclebin Lifetime (Days)',
            field=models.IntegerField(default=60, help_text='Normal users may change this value.'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='max_usage_mb',
            field=models.DecimalField(decimal_places=2, default=1000, help_text="This value CAN'T be altered by normal users", max_digits=7),
        ),
    ]
