# Generated by Django 2.2.2 on 2019-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190625_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='Recyclebin Lifetime (Days)',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='recyclebin_lifetime',
            field=models.IntegerField(default=60, help_text='Recycle bin lifetim (days). Normal users may change this value.'),
        ),
    ]
