# Generated by Django 2.2.2 on 2019-06-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190625_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='recyclebin_lifetime',
            field=models.IntegerField(default=60, help_text='Recycle bin lifetime (days). Normal users may change this value.'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
