# Generated by Django 2.2.2 on 2019-06-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_file_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='file', max_length=20),
            preserve_default=False,
        ),
    ]
