# Generated by Django 2.2.2 on 2019-06-15 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_auto_20190615_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_recycled',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
