# Generated by Django 2.2.2 on 2019-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_auto_20190615_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_recycled',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
