# Generated by Django 2.2.2 on 2019-06-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_auto_20190615_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myfiles.Folder'),
        ),
    ]
