# Generated by Django 2.2.2 on 2019-06-16 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myfiles', '0011_auto_20190615_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parent_folder_id',
        ),
        migrations.AddField(
            model_name='file',
            name='date_recycled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_recycled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myfiles.Folder'),
            preserve_default=False,
        ),
    ]
