# Generated by Django 2.2.2 on 2019-06-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_auto_20190616_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_recycled',
        ),
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_recycled',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='file',
            name='folder_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myfiles.Folder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='file', max_length=20),
        ),
    ]
