# Generated by Django 2.2.2 on 2019-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0014_auto_20190616_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
