# Generated by Django 2.2.2 on 2019-06-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0016_auto_20190625_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_shared',
        ),
    ]
