# Generated by Django 2.2.2 on 2019-06-25 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0018_folder_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
