# Generated by Django 2.2.2 on 2019-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0019_auto_20190625_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='New Folder', max_length=200),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='New Folder', max_length=200),
        ),
    ]
