# Generated by Django 2.2.2 on 2019-07-18 19:39

from django.db import migrations, models
import myfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0022_auto_20190718_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_source',
            field=models.FileField(upload_to=myfiles.models.user_directory_path),
        ),
    ]
